### ISSUE TITLE
Why it needed to access the private repo?

### ISSUE THREAD

**Issue by twentyTwo** [Sarsewar/ApexSync#1]
![image](https://user-images.githubusercontent.com/4258676/190064488-46d5cfcd-a5ef-4255-9bfe-7d13bc64a5b1.png)

While Authenticated via Github, I can see, the extension wanted to access the private repos.
Is not it a security concern?

**Comment by Sarsewar** [comment]
Hi @TwentyTwo,

Thanks for pointing this out. Initially, I developed this for my personal use, and I used "scope" as a "repo" for the creation of a private repository. Then I converted it into a Chrome Extension for public use. Currently, the extension creates a public repository and does not need private repository access. I will change the "scope" to "public_repo" as per GitHub official documentation(https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps).

Moreover, any changes in the code will need a Chrome review, and the changes will start to reflect after the Chrome review is done. It takes up to 7–30 working days, as per their official website.

Till then, you can use the extension as we are not storing any of your information, including your name, mail, and repository information. **All information is stored locally in your browser and it's completely safe to use.**

Let me know if you have concerns.

**Updates**: I have tested with the "public_repo" scope locally and it's working fine. I cannot publish it immediately because of Chome Web Store's review policy.

**Comment by Sarsewar** [comment]
@twentyTwo  
A new version with the proper scope is published on the Chrome Web Store.

![apex public repo](https://user-images.githubusercontent.com/26505197/190572978-cb17ffa2-bbb5-4333-9493-70c1704698ab.png)
