### ISSUE TITLE
Sync previously solved Problems

### ISSUE THREAD

**Issue by razu0031** [Sarsewar/ApexSync#2]
I have solved many problems previously in [apexsandbox.io ](https://www.apexsandbox.io/). How can I sync them to GitHub? 
Most of those problems are showing solved in [apexsandbox.io ](https://www.apexsandbox.io/) but the code is gone.

**Comment by Sarsewar** [comment]
Did you solve those problems on a different browser? Apexsandbox.io stores code on the browser's local cache and if you change the browser, the code will no longer be visible on the new browser. This is the exact reason I have created this extension to sync your code so that even if you change the browser, your code will be available to you.

I recommend using the browser on which you have solved those questions and try again to sync it. Or solve it again and it will sync with GitHub.

**Comment by razu0031** [comment]
I solved them about a year ago.
And Is there a way to get back the solution codes?

**Comment by Sarsewar** [comment]
Unfortunately NO. Make sure to use ApexSync this time to sync your solution to GitHub.
